"Connection"
type PostConnection implements Connection {
  pageInfo: PageInfo
  edges: [PostEdge]
}

"Edge"
type PostEdge implements Edge {
  cursor: String
  node: Post!
}

"Node"
type Post implements Node {
  """
  Post ID
  """
  id: ID!

  """
  Post text
  """
  text: String!

  """
  Post tags
  """
  tags: [String]

  """
  Post comments
  """
  comments: [Comment]
}
